# 03. DataFrame

## 📖 Introduction

A **DataFrame** is the most important data structure in Pandas.

It represents data in a **two-dimensional tabular format**, similar to an Excel spreadsheet or a SQL table.

A DataFrame consists of **rows and columns**, where:

- Each **column** is a Pandas Series.
- All columns together form a DataFrame.

Because real-world datasets are usually stored in rows and columns, DataFrames are the primary structure used for data analysis, data cleaning, feature engineering, and machine learning.

# 🎯 Problem Statement

Suppose a school stores student information.

For each student, the following details are recorded:

- Student Name
- Age
- Department
- Marks

If we use a Series, we can store only one column at a time.

However, in real applications, we need to store multiple related columns together.

This problem is solved using a **DataFrame**.

# 🤔 What is a DataFrame?

A **DataFrame** is a two-dimensional labeled data structure provided by Pandas.

It stores data in the form of **rows and columns**, making it similar to an Excel sheet or a database table.

Each column in a DataFrame is actually a Pandas Series.

### Visual Representation

| Name | Age | Department | Marks |
|------|----:|------------|------:|
| Rahul | 21 | CSE | 92 |
| Priya | 20 | ISE | 87 |
| Amit | 22 | ECE | 78 |
| Sneha | 21 | CSE | 95 |

Here:

- Rows represent individual records.
- Columns represent different features (attributes).

# 🤔 What is a DataFrame?

A **DataFrame** is a two-dimensional labeled data structure provided by Pandas.

It stores data in the form of **rows and columns**, making it similar to an Excel sheet or a database table.

Each column in a DataFrame is actually a Pandas Series.

### Visual Representation

| Name | Age | Department | Marks |
|------|----:|------------|------:|
| Rahul | 21 | CSE | 92 |
| Priya | 20 | ISE | 87 |
| Amit | 22 | ECE | 78 |
| Sneha | 21 | CSE | 95 |

Here:

- Rows represent individual records.
- Columns represent different features (attributes).

In [6]:
# 💡 Why Do We Need a DataFrame?

Imagine managing student records.

Using separate Series:

```
Names

Rahul

Priya

Amit

Marks

92

87

78

Department

CSE

ISE

ECE
```

Managing relationships between multiple Series becomes difficult.

A DataFrame stores all related information together in a structured table.

### Benefits

- Organizes data efficiently.
- Easy to filter and sort.
- Supports multiple data types.
- Easy to analyze.
- Compatible with Machine Learning libraries.

SyntaxError: invalid syntax (3181151787.py, line 3)

# ⚖️ Difference Between Series and DataFrame

| Series | DataFrame |
|--------|-----------|
| One-dimensional | Two-dimensional |
| Single column | Multiple columns |
| Represents one feature | Represents an entire dataset |
| Can have one data type | Different columns can have different data types |
| Suitable for simple data | Suitable for real-world datasets |

### Example

Series

```
Rahul

Priya

Amit
```

DataFrame

| Name | Age | Marks |
|------|----:|------:|
| Rahul | 21 | 92 |
| Priya | 20 | 87 |
| Amit | 22 | 78 |

# 🧠 Think Like a Data Scientist

Almost every dataset you work with will be loaded as a **DataFrame**.

Examples:

- Customer data
- Employee records
- Hospital records
- Sales reports
- Banking transactions
- Netflix movies
- Titanic passengers

If you know DataFrames well, you already understand the foundation of most Pandas operations.

# 3.1 Creating a DataFrame from a Dictionary

## 📖 Definition

A DataFrame can be created from a **Python dictionary**, where:

- Each **key** becomes a column name.
- Each **value** becomes the data of that column.
- Every value should generally be a list (or another iterable) of the same length.

This is the **most common and beginner-friendly** way to create a DataFrame.

---

## 🤔 Why do we need it?

While learning Pandas, we often don't have a CSV file ready.

Instead of downloading a dataset every time, we can quickly create our own dataset using a dictionary.

It is also useful for:

- Testing new code
- Creating sample datasets
- Demonstrating examples
- Unit testing
- Interview coding questions

---

## 🧠 Think Like a Data Scientist

Imagine your manager asks you to quickly test a new data cleaning function.

Instead of waiting for the production dataset, you create a small sample dataset using a dictionary and verify your logic in a few seconds.

This is why Data Scientists frequently use dictionaries while experimenting.

---

## 📌 Syntax

```python
pd.DataFrame(data)
```

or

```python
pd.DataFrame(dictionary_name)
```

where:

- `pd` → Alias for the Pandas library.
- `DataFrame` → Pandas class used to create a table.
- `data` → Dictionary containing the dataset.

In [ ]:
import pandas as pd

## 📌 Creating a Student Dataset

In [ ]:
student_data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha"],
    "Age": [21, 20, 22, 21],
    "Department": ["CSE", "ISE", "ECE", "CSE"],
    "Marks": [92, 87, 78, 95]
}

student_data

{'Name': ['Rahul', 'Priya', 'Amit', 'Sneha'],
 'Age': [21, 20, 22, 21],
 'Department': ['CSE', 'ISE', 'ECE', 'CSE'],
 'Marks': [92, 87, 78, 95]}

### 🔍 Explanation

Notice that this is still a **Python dictionary**, not a DataFrame.

Each key represents a future column.

Each list contains the values for that column.

Nothing is tabular yet.

In [ ]:
df = pd.DataFrame(student_data)

df

    Name  Age Department  Marks
0  Rahul   21        CSE     92
1  Priya   20        ISE     87
2   Amit   22        ECE     78
3  Sneha   21        CSE     95


## 🔍 Output Explanation

Let's understand each part of the output.

### 1️⃣ Left-most Numbers

```
0
1
2
3
```

These are called the **index**.

Since we didn't provide one, Pandas automatically created a default integer index starting from `0`.

---

### 2️⃣ Column Names

```
Name

Age

Department

Marks
```

These came from the **dictionary keys**.

Every key becomes one column.

---

### 3️⃣ Rows

Each horizontal record represents one student.

```
Rahul

21

CSE

92
```

is one complete row.

---

### 4️⃣ Columns

Each vertical section represents one feature.

For example,

```
Marks
```

contains the marks of all students.

---

### 5️⃣ Shape

This DataFrame has:

- **4 rows**
- **4 columns**

So its shape is:

```
(4, 4)
```

In [ ]:
type(student_data)

dict

In [ ]:
type(df)

pandas.DataFrame

# ⚠️ Common Beginner Mistakes

### ❌ Mistake 1

Using lists of different lengths.

```python
data = {
    "Name": ["Rahul", "Priya"],
    "Marks": [92, 87, 78]
}

pd.DataFrame(data)
```

### Error

```
ValueError:
All arrays must be of the same length
```

### Why did this happen?

Every column in a DataFrame must contain the **same number of rows**.

Here,

```
Name

↓

2 values
```

```
Marks

↓

3 values
```

Pandas doesn't know how to align them.

### ✅ Correct Solution

```python
data = {
    "Name": ["Rahul", "Priya", "Amit"],
    "Marks": [92, 87, 78]
}
```

In [ ]:
wrong_data = {
    "Name": ["Rahul", "Priya"],
    "Marks": [92, 87, 78]
}

# Uncomment to see the error
# pd.DataFrame(wrong_data)

# 🔄 Alternative Approaches

A DataFrame can also be created from:

- Dictionary of Lists ✅ (Today's method)
- List of Dictionaries
- List of Lists
- List of Tuples
- NumPy Arrays
- CSV Files
- Excel Files
- JSON Files

We will learn each of these in the upcoming sections.

# ✅ Pros

- Very easy to understand.
- Readable and clean.
- Best for creating small datasets.
- Frequently used in interviews.
- Excellent for testing code.

# ❌ Cons

- Not suitable for very large datasets.
- Manual data entry becomes difficult.
- Real-world datasets are usually loaded from external files.

# ⚠️ Edge Cases

### Edge Case 1

Can a DataFrame contain different data types?

Yes.

Example:

| Name | Age | Passed |
|------|----:|--------|
|Rahul|21|True|
|Priya|20|False|

A DataFrame supports multiple data types in different columns.

---

### Edge Case 2

Can a column contain missing values?

Yes.

```python
"Marks":[92,None,87]
```

Pandas automatically represents missing numeric values as `NaN`.

# 🏭 Real Industry Usage

Creating DataFrames from dictionaries is commonly used for:

- Unit testing
- Demonstrating examples
- API response processing
- Temporary datasets
- Interview coding rounds

# 🧠 Interview Corner

### Q1. What is the most common way to create a DataFrame?

**Answer:**

Using a Python dictionary.

---

### Q2. What becomes the column names?

**Answer:**

The dictionary keys.

---

### Q3. What happens if the lists have different lengths?

**Answer:**

Pandas raises:

```
ValueError:
All arrays must be of the same length
```

---

### Q4. Can a DataFrame have different data types in different columns?

**Answer:**

Yes. Each column can store a different data type.

# 📝 Assignment

Create an **Employee DataFrame** with the following columns:

- Employee_ID
- Name
- Department
- Salary
- Experience

Tasks:

1. Create the DataFrame.
2. Print it.
3. Check its type.
4. Count the number of rows and columns manually.
5. Intentionally create lists of different lengths and observe the error.

# 🚀 Mini Challenge

Create a **Product Inventory DataFrame** with the following columns:

- Product Name
- Category
- Price
- Stock

Then answer:

1. How many rows are present?
2. How many columns are present?
3. Which dictionary keys became the column names?
4. What happens if one column has fewer values?

# 3.2 Creating a DataFrame with a Custom Index

## 📖 Definition

By default, Pandas assigns an integer index starting from `0`.

However, we can provide our own meaningful row labels while creating a DataFrame. These labels are called **custom indexes**.

A custom index makes the dataset easier to understand and access, especially when the rows already have unique identifiers.

---

## 🤔 Why do we need a Custom Index?

In real-world datasets, rows often have unique identifiers instead of simple numbers.

Examples:

- Student ID
- Employee ID
- Product ID
- Order ID
- Customer ID

Instead of:

```
0
1
2
3
```

we can use:

```
S101
S102
S103
S104
```

This makes the data more meaningful and easier to work with.

---

## 🧠 Think Like a Data Scientist

Imagine a company has 50,000 employees.

Finding an employee using row number `12546` is not practical.

Instead, employees are identified using IDs like:

```
EMP1001
EMP1002
EMP1003
```

These IDs become the DataFrame index.

---

## 📌 Syntax

```python
pd.DataFrame(data, index=index_labels)
```

where:

- `data` → Dictionary or other data source.
- `index` → List containing custom row labels.

In [ ]:
student_data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha"],
    "Age": [21, 20, 22, 21],
    "Department": ["CSE", "ISE", "ECE", "CSE"],
    "Marks": [92, 87, 78, 95]
}

student_data

{'Name': ['Rahul', 'Priya', 'Amit', 'Sneha'],
 'Age': [21, 20, 22, 21],
 'Department': ['CSE', 'ISE', 'ECE', 'CSE'],
 'Marks': [92, 87, 78, 95]}

## Creating a DataFrame with Default Index

In [ ]:
import pandas as pd
df_default = pd.DataFrame(student_data)

df_default

    Name  Age Department  Marks
0  Rahul   21        CSE     92
1  Priya   20        ISE     87
2   Amit   22        ECE     78
3  Sneha   21        CSE     95

## Creating a DataFrame with Custom Index

In [ ]:
student_index = ["S101", "S102", "S103", "S104"]

df = pd.DataFrame(student_data, index=student_index)

df

       Name  Age Department  Marks
S101  Rahul   21        CSE     92
S102  Priya   20        ISE     87
S103   Amit   22        ECE     78
S104  Sneha   21        CSE     95

## 🔍 Output Explanation

Let's understand what changed.

### Before

```
0
1
2
3
```

These were automatically generated by Pandas.

### After

```
S101
S102
S103
S104
```

These are the custom indexes we supplied.

Notice that:

- The data has not changed.
- Only the row labels have changed.
- Each row now has a meaningful identifier.

# 🧩 Visualizing the DataFrame

```
             Columns
        -------------------------
Index    Name  Age  Dept  Marks
--------------------------------
S101    Rahul  21   CSE    92
S102    Priya  20   ISE    87
S103    Amit   22   ECE    78
S104    Sneha  21   CSE    95
```

Here:

- Left side → **Index**
- Top → **Column Names**
- Middle → **Cell Values**

In [ ]:
df.index

Index(['S101', 'S102', 'S103', 'S104'], dtype='str')

## 📤 Expected Output

```
Index(['S101', 'S102', 'S103', 'S104'], dtype='object')
```

### 🔍 Explanation

The `index` attribute returns all row labels of the DataFrame.

This is useful when you want to inspect or modify row labels.

# ⚠️ Common Beginner Mistakes

### ❌ Mistake 1

Providing fewer index labels than rows.

```python
pd.DataFrame(student_data,
             index=["S101", "S102"])
```

### Error

```
ValueError:
Length of values does not match length of index
```

### Why?

The DataFrame has **4 rows**, but only **2 index labels** were provided.

Every row must have exactly one index label.

### ✅ Correct Solution

```python
index=["S101","S102","S103","S104"]
```

# ✅ Pros

- Makes the dataset more meaningful.
- Easy to identify records.
- Useful for searching and selecting rows.
- Common in business datasets.

# ❌ Cons

- Duplicate index labels can create confusion.
- Very long index labels reduce readability.

# ⚠️ Edge Cases

### Can indexes be strings?

✅ Yes

```
EMP101
EMP102
```

---

### Can indexes be integers?

✅ Yes

```
101
102
103
```

---

### Can indexes be dates?

✅ Yes

```
2026-08-01

2026-08-02
```

Pandas supports many index types.

# 🏭 Real Industry Usage

Custom indexes are widely used for:

- Employee IDs
- Student IDs
- Customer IDs
- Product IDs
- Invoice Numbers
- Transaction IDs

Instead of meaningless row numbers, organizations use business identifiers.

# 🧠 Interview Corner

### Q1. What is the default DataFrame index?

A sequence of integers starting from **0**.

---

### Q2. Why do we use a custom index?

To uniquely identify rows using meaningful labels such as Employee IDs or Student IDs.

---

### Q3. What happens if the number of index labels doesn't match the number of rows?

Pandas raises a **ValueError** because every row must have exactly one index label.

---

### Q4. Can a DataFrame have string indexes?

Yes. Index labels can be strings, integers, dates, and many other data types.

# 📝 Assignment

Create an Employee DataFrame with:

- Employee_ID (use as custom index)
- Name
- Department
- Salary
- Experience

Tasks:

1. Create the DataFrame.
2. Display the index.
3. Explain the difference between the default index and the custom index.
4. Try providing only three index labels for four rows and observe the error.

# 🚀 Mini Challenge

A college stores student information.

Use the following Student IDs as the index:

```
ST101
ST102
ST103
ST104
```

Create a DataFrame with:

- Name
- Branch
- CGPA

After creating it:

- Print the DataFrame.
- Display the index.
- Explain why using Student IDs is better than using `0, 1, 2, 3`.

# 3.3 DataFrame Attribute - `shape`

## 📖 Definition

The `shape` attribute returns the **number of rows and columns** present in a DataFrame.

It returns the result as a **tuple** in the form:

```python
(rows, columns)
```

Unlike methods such as `head()` or `describe()`, `shape` is an **attribute**, so it is accessed **without parentheses**.

---

## 🤔 Why do we use `shape`?

Whenever we receive a new dataset, the first question is:

- How many records are present?
- How many features (columns) are available?

Instead of counting them manually, we simply use:

```python
df.shape
```

This instantly tells us the size of the dataset.

---

## 🧠 Think Like a Data Scientist

Imagine your manager sends you a customer dataset.

Before doing any analysis, you need to know:

- Is it a small dataset?
- Is it a large dataset?
- How many features are available?

The first command you will most likely run is:

```python
df.shape
```

This gives you a quick overview of the dataset.

In [ ]:
import pandas as pd

student_data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha"],
    "Age": [21, 20, 22, 21],
    "Department": ["CSE", "ISE", "ECE", "CSE"],
    "Marks": [92, 87, 78, 95]
}

df = pd.DataFrame(student_data)

df

    Name  Age Department  Marks
0  Rahul   21        CSE     92
1  Priya   20        ISE     87
2   Amit   22        ECE     78
3  Sneha   21        CSE     95

## 📌 Syntax

```python
df.shape
```

Since `shape` is an **attribute**, we do **not** write parentheses.

❌ Incorrect

```python
df.shape()
```

✅ Correct

```python
df.shape
```

In [ ]:
df.shape

(4, 4)

## 📤 Expected Output

```python
(4, 4)
```

---

## 🔍 Output Explanation

The output is a tuple:

```
(rows, columns)
```

For our DataFrame:

- Rows = **4**
- Columns = **4**

Therefore:

```python
(4, 4)
```

### 🧩 Visualization

```
            Name    Age   Department   Marks
---------------------------------------------
Row 1       Rahul    21      CSE         92
Row 2       Priya    20      ISE         87
Row 3       Amit     22      ECE         78
Row 4       Sneha    21      CSE         95
---------------------------------------------
            ↑
         4 Rows

Columns →

Name | Age | Department | Marks

= 4 Columns

Shape = (4, 4)
```

In [ ]:
rows, columns = df.shape

print("Number of Rows    :", rows)
print("Number of Columns :", columns)

Number of Rows    : 4
Number of Columns : 4

## 🔍 Explanation

Since `shape` returns a tuple, we can unpack it into two variables.

```python
rows, columns = df.shape
```

Now:

- `rows` stores the number of rows.
- `columns` stores the number of columns.

This is commonly used in machine learning pipelines and data validation scripts.

# ⚠️ Common Beginner Mistakes

### ❌ Mistake 1

Writing:

```python
df.shape()
```

### Error

```python
TypeError: 'tuple' object is not callable
```

### Why?

`shape` is an **attribute**, not a method.

### ✅ Correct

```python
df.shape
```

---

### ❌ Mistake 2

Thinking:

```python
(4, 4)
```

means

```
(columns, rows)
```

Actually:

```
(rows, columns)
```

Always remember:

```python
(rows, columns)
```

# ✅ Pros

- Very fast.
- Gives an instant overview of the dataset.
- Useful before cleaning or modeling.
- Used in almost every Pandas workflow.

# ❌ Cons

- Does not show column names.
- Does not show data types.
- Does not show missing values.

For those tasks, use methods like `columns`, `dtypes`, and `info()`.

# ⚠️ Edge Cases

### Edge Case 1

A DataFrame with **zero rows**:

```python
pd.DataFrame(columns=["A", "B"])
```

Shape:

```python
(0, 2)
```

There are **0 rows** but **2 columns**.

---

### Edge Case 2

A DataFrame with **one row**:

```python
(1, 4)
```

The `shape` attribute still returns:

```python
(rows, columns)
```

# 🏭 Real Industry Usage

The `shape` attribute is commonly used to:

- Verify that a dataset loaded correctly.
- Check whether rows were removed after cleaning.
- Compare dataset size before and after preprocessing.
- Validate input data before training machine learning models.

# 🧠 Interview Corner

### Q1. What does `shape` return?

It returns a tuple containing:

```python
(rows, columns)
```

---

### Q2. Is `shape` a method or an attribute?

It is an **attribute**.

---

### Q3. Why don't we write parentheses with `shape`?

Because attributes store values, while methods perform actions.

---

### Q4. What is the shape of a DataFrame with 100 rows and 8 columns?

```python
(100, 8)
```

# 3.4 DataFrame Attribute - `size`

## 📖 Definition

The `size` attribute returns the **total number of elements** present in a DataFrame.

It is calculated as:

```python
Number of Rows × Number of Columns
```

Unlike `shape`, which returns two values, `size` returns a **single integer**.

`size` is an **attribute**, so it is accessed **without parentheses**.

---

## 🤔 Why do we use `size`?

Sometimes we want to know the total number of values stored in a dataset.

Instead of manually multiplying the number of rows and columns, Pandas provides the `size` attribute.

This is useful for:

- Quickly understanding dataset size
- Data validation
- Comparing datasets before and after preprocessing

---

## 🧠 Think Like a Data Scientist

Suppose your team receives two datasets.

Dataset A

```
500 rows
8 columns
```

Dataset B

```
1000 rows
12 columns
```

To estimate how much data each contains, one quick metric is the **total number of elements**, which you can obtain using:

```python
df.size
```

In [ ]:
import pandas as pd

student_data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha"],
    "Age": [21, 20, 22, 21],
    "Department": ["CSE", "ISE", "ECE", "CSE"],
    "Marks": [92, 87, 78, 95]
}

df = pd.DataFrame(student_data)

df

    Name  Age Department  Marks
0  Rahul   21        CSE     92
1  Priya   20        ISE     87
2   Amit   22        ECE     78
3  Sneha   21        CSE     95

## 📌 Syntax

```python
df.size
```

Since `size` is an **attribute**, do **not** use parentheses.

✅ Correct

```python
df.size
```

❌ Incorrect

```python
df.size()
```

In [ ]:
df.size

16

## 📤 Expected Output

```python
16
```

---

## 🔍 Output Explanation

Our DataFrame contains:

- Rows = **4**
- Columns = **4**

Therefore,

```
Total Elements

=

Rows × Columns

=

4 × 4

=

16
```

### 🧩 Visualization

```
            Name   Age   Department   Marks
--------------------------------------------
Rahul      1      2         3          4

Priya      5      6         7          8

Amit       9     10        11         12

Sneha     13     14        15         16
--------------------------------------------

Total Elements = 16
```

In [ ]:
print("Shape :", df.shape)
print("Size  :", df.size)

Shape : (4, 4)
Size  : 16

## 🔍 Understanding the Difference

Output:

```python
Shape : (4, 4)
Size  : 16
```

Explanation:

- `shape` tells us the **structure** of the DataFrame (rows and columns).
- `size` tells us the **total number of values** stored in the DataFrame.

Formula:

```python
df.size == df.shape[0] * df.shape[1]
```

In [ ]:
rows, columns = df.shape

print("Rows :", rows)
print("Columns :", columns)

print("Calculated Size :", rows * columns)
print("Actual Size     :", df.size)

Rows : 4
Columns : 4
Calculated Size : 16
Actual Size     : 16

# ⚠️ Common Beginner Mistakes

### ❌ Mistake 1

Writing:

```python
df.size()
```

### Error

```python
TypeError: 'int' object is not callable
```

### Why?

`size` is an **attribute**, not a method.

### ✅ Correct

```python
df.size
```

---

### ❌ Mistake 2

Thinking `size` returns the number of rows.

Actually:

```python
size = rows × columns
```

It returns the **total number of elements**, not the number of rows.

# ✅ Pros

- Very fast.
- Gives the total number of values instantly.
- Useful for quick dataset validation.
- Helpful when comparing dataset sizes.# ❌ Cons

- Does not show rows and columns separately.
- Does not provide column names.
- Does not show data types.

# ⚠️ Edge Cases

### Edge Case 1

Empty DataFrame

```python
empty_df = pd.DataFrame(columns=["A", "B"])

empty_df.shape
# (0, 2)

empty_df.size
# 0
```

Although there are **2 columns**, there are **0 stored values**.

---

### Edge Case 2

Single Row DataFrame

```
Shape

↓

(1, 4)

Size

↓

4
```

# 🏭 Real Industry Usage

The `size` attribute is commonly used for:

- Checking dataset size after preprocessing.
- Comparing datasets before and after feature engineering.
- Validating transformed datasets in ETL pipelines.
- Logging dataset statistics during machine learning workflows.

# 🧠 Interview Corner

### Q1. What does `size` return?

It returns the **total number of elements** in the DataFrame.

---

### Q2. How is `size` calculated?

```python
Rows × Columns
```

---

### Q3. Is `size` a method or an attribute?

It is an **attribute**.

---

### Q4. A DataFrame has 200 rows and 15 columns. What is its size?

```
200 × 15 = 3000
```

# 📝 Assignment

Create a DataFrame containing:

- Product Name
- Category
- Price
- Stock
- Supplier

Tasks:

1. Print the DataFrame.
2. Display its `shape`.
3. Display its `size`.
4. Verify that:

```python
rows × columns = size
```

# 🚀 Mini Challenge

Create a **Hospital DataFrame** with the following columns:

- Patient Name
- Age
- Disease
- Ward
- Doctor

Tasks:

1. Print the DataFrame.
2. Find its `shape`.
3. Find its `size`.
4. Explain why `shape` and `size` return different outputs.